name: Deploy app

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      - name: install dependencies
        run:  npx pnpm install

      - name: run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DOMAIN: ${{ secrets.DOMAIN }}
          ENCRYPT_INITIAL_VECTOR: ${{ secrets.ENCRYPT_INITIAL_VECTOR }}
          ENCRYPT_SECRET: ${{ secrets.ENCRYPT_SECRET }}
          JWT_EXPIRES_IN: ${{ secrets.JWT_EXPIRES_IN }}
          JWT_REFRESH_EXPIRES_IN: ${{ secrets.JWT_REFRESH_EXPIRES_IN }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

        run: |
          npx pnpm run build
          npx pnpm run start:production
